AllCops:
  TargetRubyVersion: 2.4

Metrics/ModuleLength:
  Max: 500

Metrics/BlockLength:
  Max: 500

Metrics/MethodLength:
  Max: 50

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: same_line

Layout/LineLength:
  Max: 100