name: Ruby Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x
    - name: Run tests for production
      env:
        appSid: ${{secrets.appSidProd}}
        appKey: ${{secrets.appKeyProd}}
        apiBaseUrl: "https://api.aspose.cloud"
      run: |
        gem install -g
        rspec -t pipeline spec
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
    - name : Create release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Release notes available at https://docs.aspose.cloud/display/emailcloud/Aspose.Email+Cloud+${{github.ref#*/v}}+Release+Notes
        draft: false
        prerelease: false
     
