name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Test with Rspec
      env:
        clientId: ${{secrets.appSid}}
        clientSecret: ${{secrets.appKey}}
        apiBaseUrl: "https://api-qa.aspose.cloud"
      run: rspec -t pipeline spec
