name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Test with Rspec
      env:
        clientId: ${{secrets.appSidProd}}
        clientSecret: ${{secrets.appKeyProd}}
        apiBaseUrl: "https://api.aspose.cloud"
      run: bundle exec rspec -t pipeline spec
